name:  Deploy Adapter Service

on:
  pull_request:
    branches:
      - develop
    paths:
      - src/adapter/**
      - src/common/**
    types: [closed]

jobs:
  deploy-dev:
     runs-on: ubuntu-latest
     if: github.event.pull_request.merged == true
     steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Source PYTHONPATH
        run: source export_for_local_test.sh
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install packages
        run: pip install -r requirements.txt
      - name: Configure AWS Dev profile
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Use Node.js version 12
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install Serverless and its dependencies
        run: |
          cd services/adapter_service/
          npm install -g serverless
          serverless plugin install --name serverless-python-requirements --stage dev
          serverless plugin install --name serverless-plugin-aws-alerts --stage dev
          serverless plugin install --name serverless-package-external --stage dev
          cd ../../
      - name: Deploy Adapter Service
        run: |
          cd services/adapter_service/
          serverless deploy  --stage dev --region us-east-1
          cd ../../