name: Test Adapter Service

on:
  pull_request:
     branches:
      - develop
     paths:
      - src/adapter/**
      - src/common/**
  push:
    paths:
      - src/adapter/**
      - src/common/**

jobs:
  Linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - run: pip install pylint  # -r requirements.txt
      - run: pylint src/adapter/*.py --rcfile pylintrc --output-format=colorized 
  coverage:
    runs-on: ubuntu-latest

    steps:
        # Checkout the latest code from the repo
      - name: Checkout repo
        uses: actions/checkout@v2
        # Setup which version of Python to use
      - name: Source PYTHONPATH
        run: source export_for_local_test.sh
      - name: Set Up Python 
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
        # Display the Python version being used
      - name: Install common package
        run: pip3 install -r requirements.txt
      - name: Install oauth packages
        run: pip3 install -r src/common/authentication/requirements.txt
        # Install pytest (you can use some other testing utility)
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
        # Run the tests. I'm using pytest and the file is in the tests directory.
      # - name: Run tests
      #   run: coverage run --omit 'utility/*' -m services/adapter/tests/ services/flow/tests/  services/filter/tests/ services/transformer/tests/
      - name: Coverage report
        run: |
          pip install coverage moto
          pip install attrs==21.2.0
          MIN_COVERAGE=85
          coverage run --omit 'src/common/*' -m pytest src/adapter/tests/ src/common/authentication/tests/
          coverage report -m
          coverage html
          COVERAGE=$(coverage report -m | grep -i "TOTAL" | awk '{print $4}' | sed 's/%//')
          if [ "$COVERAGE" -lt "$MIN_COVERAGE" ]; then exit 1; else exit 0; fi
        env:
          PYTHONPATH: '../../src/:../src:./src/:/../:./src/common/:./services/:./services/flow/:$PYTHONPATH'
          ORACLE_NETSUITE_BASE_URL: 'https://TSTDRV1667270.suitetalk.api.netsuite.com'
      # - name: Archive production artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: dist-without-markdown
      #     path: |
      #       - htmlcov/
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: htmlcov/
